name: multiversx_sdk
description: MultiversX SDK for Dart
version: 0.1.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  convert: ^3.1.0
  http: ^1.2.2
  meta: ^1.12.0
  multiversx_api:
    path: ../api
  multiversx_crypto:
    path: ../crypto
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  lints: ^4.0.0
  mockito: ^5.4.4
  test: ^1.25.0
