name: multiversx_crypto
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  bip39: ^1.0.6
  convert: ^3.1.1
  ed25519_hd_key: ^2.3.0
  pinenacl: ^0.6.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
