name: multiversx_crypto
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  bip39: ^1.0.6
  convert: ^3.1.1
  ed25519_hd_key: 
    git:
      url: https://github.com/KLEAK-Development/dart-ed25519-hd-key.git
      ref: 5faf7d72812445ce02c30fd34f85b5b8906498d6
  pinenacl: ^0.6.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
